apiVersion: batch/v1
kind: CronJob
metadata:
  name: apel-parser
spec:
  schedule: "0 8 * * *"
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
          containers:
            - name: apel-parser
              image: registry.cern.ch/wlcg-ops/apel-parser:latest
              imagePullPolicy: Always
              command:
                - "python3"
                - "/app/message_parser.py"
                - "-o"
                - "/var/spool/apel/parser_output"
                - "--messages-dir"
                - "/var/spool/apel/grid/incoming"
                - "-m"
                - "15"
                # - "--lhc-only"
                - "--publish"
              env:
                - name: MQ_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mq-creds
                      key: username
                - name: MQ_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mq-creds
                      key: password
                - name: MQ_HOST
                  valueFrom:
                    secretKeyRef:
                      name: mq-creds
                      key: host
                - name: MQ_PORT
                  valueFrom:
                    secretKeyRef:
                      name: mq-creds
                      key: port
                - name: MESSAGE_TOPIC
                  value: "wlcgops.accounting.space"
                - name: MESSAGE_PRODUCER
                  value: "wlcgops"
                - name: MESSAGE_INFLUXDB_MEASUREMENT
                  value: "accounting.wau.summary_apel_4"
              volumeMounts:
                - name: apel-consumer-output
                  mountPath: /var/spool/apel
                - name: cvmfs
                  subPath: grid.cern.ch
                  mountPath: /cvmfs/grid.cern.ch
                  mountPropagation: HostToContainer
          volumes:
            - name: apel-consumer-output
              persistentVolumeClaim:
                claimName: apel-consumer-output
            - name: cvmfs
              persistentVolumeClaim:
                claimName: cvmfs
